### ISSUE TITLE
CHORE: Investigate if this extension is obsolete

### ISSUE THREAD

**Issue by pichfl** [pichfl/NoMoreiTunes#12]
After testing a few links, it seems that we're just fine without this extension now. Which is nice.

**Comment by Fofer** [comment]
Now I'd love to see the opposite extension, that would open iTunes 12.6.3 when we come across iTunes Preview pages for apps.  Because now that the button is gone from the web page, we have to manually switch to iTunes and search for the same app.

**Comment by pichfl** [comment]
Oh interesting 😯 I never considered this before, but you are right! Don't expect an update until end of December though, my spare time is limited but the holidays provide some opportunities.

**Comment by Fofer** [comment]
Thanks for the consideration!  I work in IT and development and there are many of use who now have to hold on to iTunes 12.6.3 for app searching, browsing, research and purchasing. Apple's disconnect of the iOS App Store from the Mac/PC versions of iTunes has made this work a bit more of a chore. So a simple link added back to the App Store's webpage,s that brings us to the appropriate page in the App Store still available via iTunes 12.6.3 would be very much appreciated.  If it works out that you're able to update this extension for that, it would be very cool. Happy holidays!

**Comment by Fofer** [comment]
Just for reference, this is how Apple has added the button on the web pages for apps that are available in the Mac App Store:
http://i.imgur.com/0FELUM7.png
https://itunes.apple.com/us/app/ezzi-keyboard/id1069314102?mt=12

If something similar could be added to web pages for iOS apps that are available in the iOS App Store inside iTunes 12.6.3, that would be amazing :)

**Comment by pichfl** [comment]
Closing in favor of #16
