### ISSUE TITLE
Cannot Install In Safari 9.1.2 (El Capitan 10.11.6)

### ISSUE THREAD

**Issue by EdmondsonJames** [pichfl/NoMoreiTunes#8]
Tried to install, got error message: "This extension is not from the Safari Extensions Gallery. You should only install extensions from sources you trust." Clicked "Trust" but did not install. Thanks.

**Comment by pichfl** [comment]
Thanks for the info, it seems I have to create a new version anyway. I'm looking into it.

**Comment by EdmondsonJames** [comment]
There is a workaround for installation, then it works: 
(1) System Preferences > Keyboard > Shortcuts > (Full Keyboard Access) All Controls
(2) Double click Safari Extension icon to try to install it, get warning notice, tab to highlight “Trust” (do not click with cursor), hit spacebar
(3) Extension installs and works as it always has in previous version of Safari/OSX

The only changes you might need to consider are either to describe the above workaround on your website or to get it into the Safari Extensions Gallery so that the warning does not appear.

Jim

**Comment by pichfl** [comment]
I tried to get into the Gallery a few times, sadly since this modifies Apple intended behavior I had little luck yet.

**Comment by pichfl** [comment]
This will resolve once #16 is done.
